### ISSUE TITLE
Missing protobuf support

### ISSUE THREAD

**Issue by grobie** [prometheus/client_ruby#10]
There is currently no support for prometheus' protobuf format. The format is described here: http://prometheus.io/docs/instrumenting/exposition_formats/. 

The protobuf definition itself has been created already: https://github.com/prometheus/client_model/tree/master/ruby.

**Comment by beorn7** [comment]
Just as a side note: The new Java client ("simple client") doesn't support protobuf yet, either. To vet the urgency of adding the support, we ran some benchmarks to find out how much network and server resources the different formats require. The result was that protobuf parsing is much faster than the text format (which is in turn a bit faster than JSON parsing). Uncompressed, the protobuf format is smaller than the text format, but compressed, there is not much difference. However, if you apply compression, the relative difference between protobuf and text format it terms of parsing effort shrinks as the de-compression step takes a similar amount of time for both formats. While the gain of the text format over the deprecated JSON format seems small in comparison, it is enough to get down to a resource usage where other things become more important. Even with pure text format clients, you'll probably be able to support most of the use cases. Only for very high throughput cases (tens of thousands of samples ingested per sec), it will matter if you use protobuf or not.
So it is still an improvement to support protobuf, but other things might be more urgent to implement first.

**Comment by grobie** [comment]
Protobuf support has been removed in Prometheus 2.0
