### ISSUE TITLE
Add 'Upgrading' section to README for people upgrading from versions predating multi-process support

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#104]
As part of our work in #95 to introduce multi-process support, we made several breaking changes to the interface of the library.

To ease the transition for existing users, we should provide some documentation on the changes.

**Comment by rsetia** [comment]
https://github.com/gocardless/prometheus_client_ruby/pull/6

PR that adds documentation in a separate UPGRADE.md file. Feel free to copy it into README.md if that's preferred.

**Comment by Sinjo** [comment]
Gonna pick up the work from #125, update it with any changes we've made since, and get this over the line. Hopefully get some time to do it tomorrow!

**Comment by dmagliola** [comment]
Closed by #125
