### ISSUE TITLE
Document that `DirectFileStore` is more memory-hungry than other stores

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#106]
From running it in production, we (GoCardless) have found DirectFileStore to be more memory-hungry than other ways of storing metrics.

This isn't entirely surprising, but we've done a little investigation into whether we could reduce the effect and we may have some improvements we can make.

One mitigation we found after looking round the internet was to switch from libc malloc to jemalloc, which mitigates a lot of the memory bloat issues you can run into with CRuby.

For now it's sufficient for us to document this and move on.

One of our internal users found some potential savings on memory allocations (hence bloat), which we can look to apply later, but which don't block releasing multi-process support.

**Comment by dmagliola** [comment]
Closed by #167
