### ISSUE TITLE
Review approach to file globbing when reading metrics

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#108]
One of our internal users raised a point about our method of reading PID files when exporting metrics making it possible to accidentally include more files than it should. Specifically, if one metric name is a subset of another, the export of the metric with the subset name could include values from the metric with a longer name.

@dmagliola commented that running into this issue would involve putting a triple underscore in your metric name, which is highly unusual and against conventions, but maybe we can choose a character that never appears in metric names when we generate the file names.

At a minimum, if we make no code change, we should document the behaviour.

**Comment by dmagliola** [comment]
My 2 cents... This *really* feels like one of those theoretically serious issues that will never actually happen. You need to have a metric `name`, and then `name___more_specific` (with a triple underscore). The triple underscore needs to be placed in a very precise place. 

I can change the `___` to `___please_dont_seriously___`, but it doesn't feel like a great solution. I vote to close this.

**Comment by dmagliola** [comment]
I'm closing this, on account of my previous comment, and the lack of objections. Feel free to reopen if you feel strongly about this.
