### ISSUE TITLE
Resolve discussion on pre-set label values

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#112]
These have been [pointed out](https://github.com/prometheus/client_ruby/pull/95#discussion_r262053645) as a feature that gets abused.

Right now I’m not exactly sure what that abuse typically looks like, but maybe there are Prometheus docs that talk about it.

Is the abuse so bad that clients are being built without this feature now?

**Comment by brian-brazil** [comment]
The abuse is mainly using it for what should be target labels.

**Comment by dmagliola** [comment]
Relevant discussion to this issue: https://github.com/prometheus/client_ruby/pull/93

**Comment by Sinjo** [comment]
I think we can safely [consider the discussion resolved](https://github.com/prometheus/client_ruby/blob/9c896d0d60b5715f4a7928092eb9e498356dcaee/lib/prometheus/client/metric.rb#L15).
