### ISSUE TITLE
Documentation for `DirectFileStore`

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#117]
We've got a few mentions of it in `README.md` and in the stores documentation, but I think we'd do well to have specific documentation for this store, particularly around any usage constraints/requirements. I'd expect this to cover at least the caveats mentioned in [the PR that added the functionality](https://github.com/prometheus/client_ruby/pull/95) if we can't solve them more cleanly.

**Comment by dmagliola** [comment]
Closed by #167
