### ISSUE TITLE
Detect PID changes and open new store in `DirectFileStore`

### ISSUE THREAD

**Issue by Sinjo** [prometheus/client_ruby#119]
Since we're creating a store that's designed for use from multiple processes, it would be nice to more gracefully handle PID changes caused by forking gracefully.

Currently, if you wrote to a metric in the original process, the new process will continue writing to the metric file opened by the original process, as the file handle [is kept around](https://github.com/gocardless/prometheus_client_ruby/blob/5dce3e5855f2aa67c65874c953878e124c23edcd/lib/prometheus/client/data_stores/direct_file_store.rb#L147).

We'd need some sort of cache-busting-esque mechanism that caused a new metrics file to be opened when a PID change was detected.

**Note that you shouldn't be writing any metrics before you fork! Implementing this would be rounding off a sharp edge.**

**Comment by brian-brazil** [comment]
We had this issue in Python, if we detect a pid change (which we check for on every instrumentation event) we close and reopen everything.
