### ISSUE TITLE
Travis -> CircleCI

### ISSUE THREAD

**Issue by lawrencejones** [prometheus/client_ruby#133]
Travis has gone through some unfortunate times recently and CircleCI offer a more comprehensive and flexible configuration in their V2 spec.

It could be good to run CI like this: https://github.com/gocardless/statesman/blob/master/.circleci/config.yml

**Comment by Sinjo** [comment]
Would love to have a crack at this, but it looks like I need repo admin to get started.

<img width="668" alt="Screenshot 2019-10-05 at 14 30 05" src="https://user-images.githubusercontent.com/237226/66255546-ab745680-e77c-11e9-94df-3eec8a5f7073.png">

@SuperQ would you be able to help with that when you have a minute?

**Comment by Sinjo** [comment]
@SuperQ Just running through old issues and I'd like to give this one a go. Figure it makes sense for the reasons outlined by @lawrencejones and the fact that prometheus/prometheus uses CircleCI too.

Any chance I could (at least temporarily) be made admin on this repo?

**Comment by dmagliola** [comment]
Looking at the other repos, it looks like they also use Circle, so this'd make sense to me

**Comment by dmagliola** [comment]
I wonder, however, if it'd make more sense to use the "Matrix" feature, like the [Python repo does](https://github.com/prometheus/client_python/blob/master/.circleci/config.yml), instead of specifying the different versions like in Lawrence's proposal. 

Although that's a nitpick, and I may be over-reading on what he was proposing to do

**Comment by Sinjo** [comment]
I don't think Lawrence was being that specific about what Circle config we write as much as saying that we should move over to Circle. Not least because [they added build matrices](https://circleci.com/blog/circleci-matrix-jobs/) almost a year after he raised this issue.

**Comment by Sinjo** [comment]
Closing this as it's been done in #230.
