### ISSUE TITLE
Compatibility policy

### ISSUE THREAD

**Issue by lawrencejones** [prometheus/client_ruby#134]
This gem doesn't provide any official compatibility policies stating when Ruby versions are deprecated, etc.

Documenting this policy makes it easier for maintainers to keep the library up-to-date and know when to adopt modern Ruby practices/drop legacy ones.

A great starting point would be: https://github.com/gocardless/statesman/blob/master/docs/COMPATIBILITY.md

**Comment by lawrencejones** [comment]
Start of a guide is PR'd here: https://github.com/prometheus/client_ruby/pull/136

**Comment by dmagliola** [comment]
Solved by PR 136
