### ISSUE TITLE
Cant specify Histogram buckets

### ISSUE THREAD

**Issue by RaptorGandalf** [prometheus/client_ruby#150]
Im having trouble specifying buckets for a histogram control. Im not sure if this is a bug, or if I am just not understanding something.

I create a histogram like this:

```
histogram = Prometheus::Client::Histogram.new(:my_histogram,
                                              docstring: 'A histogram',
                                              labels: [:foo],
                                              buckets: [2, 4, 6, 8, 10])
```

After recording some values, and hitting the `/metrics` endpoint, the histogram values look like so:

```
# HELP my_histogram {:docstring=>"A histogram", :labels=>[:foo], :buckets=>[2, 4, 6, 8, 10]}
my_histogram_bucket{foo="bar",le="0.005"} 0.0
my_histogram_bucket{foo="bar",le="0.01"} 0.0
my_histogram_bucket{foo="bar",le="0.025"} 0.0
my_histogram_bucket{foo="bar",le="0.05"} 0.0
my_histogram_bucket{foo="bar",le="0.1"} 0.0
my_histogram_bucket{foo="bar",le="0.25"} 0.0
my_histogram_bucket{foo="bar",le="0.5"} 0.0
my_histogram_bucket{foo="bar",le="1"} 2.0
my_histogram_bucket{foo="bar",le="2.5"} 2.0
my_histogram_bucket{foo="bar",le="5"} 2.0
my_histogram_bucket{foo="bar",le="10"} 2.0
my_histogram_bucket{foo="bar",le="+Inf"} 2.0
```

It appears that the histogram control knows that I passed in my own buckets, but the values seem to be recorded using the default buckets. Is this some kind of intended functionality that I dont understand?

**Comment by dmagliola** [comment]
Hello @RaptorGandalf. Thank you for your report. I can confirm this is *not* intended behaviour. I will look into this and let you know once I've found out what's going on, but just wanted to let you know that this is not by design

**Comment by RaptorGandalf** [comment]
@dmagliola Thanks for the update! For what its worth, I recently tried the same operation on the latest 0.10 alpha release, and I did not see this issue.

**Comment by dmagliola** [comment]
Oh, if you were using that line with version 0.9, then that was definitely not going to work.
On 0.10, we changed from ordered arguments to kwargs, so your `labels` and `buckets` would've been ignored.

Can you confirm that this issue was in 0.9, and if so, close the issue?

**Comment by RaptorGandalf** [comment]
The issue was in fact in 0.9, I will close. Thanks for the help!
