### ISSUE TITLE
Labels are formatted as a string hash on the /metrics endpoint

### ISSUE THREAD

**Issue by JGShaw** [prometheus/client_ruby#155]
Gem version: 0.9.0

The labels are not being formatted correctly on the output page on /metrics. It seems to be converting the hash of labels and keeping the named argument. See the example output below to see what I believe the output should be

Counter initialisation:
```ruby
# config/initializers/prometheus.rb
prometheus = Prometheus::Client.registry
JOBS = prometheus.counter(
  :jobs,
  docstring: "number of jobs produced",
  labels: [:schema_type]
)
```

How the counter is increased:
```ruby
JOBS.increment(labels: { schema_type: schema_type.to_s })
```

The current, incorrect output:
```
# TYPE jobs counter
# HELP jobs {:docstring=>"number of jobs produced", :labels=>[:schema_type]}
jobs{labels="{:schema_type=>\"dynamic\"}"} 35.0
```

What the output should be:
```
# TYPE jobs counter
# HELP jobs number of jobs produced
jobs{schema_type="dynamic"} 35.0
```

**Comment by JGShaw** [comment]
Ive just seen that this is solved in 0.10.0.pre.alpha.2, It would be good if this was reflected in the README to make people aware of this.

**Comment by dmagliola** [comment]
@sinjo do you think this might be related to the recent stringification of labels?

**Comment by dmagliola** [comment]
Hi @JGShaw,
Sorry about that. 

This is a good point. We're in an interim point where we're working to release soon a backwards incompatible version. In the meantime, the documentation reflects the new version, but a regular gem installation will give you 0.9

@sinjo should we add a big red sign at the top of the README mentioning this doc is for a new version and we recommend manually specifying the alpha version?
