### ISSUE TITLE
Counters can be decremented

### ISSUE THREAD

**Issue by jc** [prometheus/client_ruby#16]
The prometheus documentation states that:

> Counters should not be used to expose current counts of items whose number can also go down, e.g. the number of currently running goroutines.

Currently counters can be decremented by `decrement` or passing a negative value into `increment`.

**Comment by juliusv** [comment]
Yeah, the Go client library doesn't have a `decrement` and even checks for negative `increment` values (https://github.com/prometheus/client_golang/blob/master/prometheus/counter.go#L67-L72). This should be made consistent in the Ruby client as well.

**Comment by grobie** [comment]
The client is older than the document. Makes sense.
