### ISSUE TITLE
docker log flooded with  warning: instance variable @all_labels_preset not initialized

### ISSUE THREAD

**Issue by JonJagger** [prometheus/client_ruby#190]
Hi,

My dockerized rack-server's entrypoint is

```
readonly MY_DIR="$(cd "$(dirname "${0}")" && pwd)"
export RUBYOPT='-W2'
rackup \
  --env production \
  --port ${PORT}   \
  --server puma    \
  --warn           \
    ${MY_DIR}/config.ru
```

And my config.ru, copied directly from the README.md, has

```
require 'prometheus/middleware/collector'
require 'prometheus/middleware/exporter'
use Prometheus::Middleware::Collector
use Prometheus::Middleware::Exporter
...
```

Unfortunately this floods my docker log with the following warning:

warning: instance variable @all_labels_preset not initialized

This comes from 
lib/prometheus/client/metric.rb:91

I'd really appreciate it anyone could help me by either,
telling me how to avoid this warning at 2.0.0, or
doing a new release that fixes the problem.

Thanks

**Comment by dmagliola** [comment]
Hello,
What version of Ruby are you using?

**Comment by JonJagger** [comment]
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
Sorry, should have mentioned that.

**Comment by dmagliola** [comment]
Thank you for the report!
Turns out, we're running our tests with warning off, so we're missing a bunch. 

I've opened PR #191 to fix this warning you reported and a few others.
There's also PR #188 which fixes another deprecation warning.

Once we merge both of those, i'll cut a new version of the gem. 

Thanks!
Daniel

**Comment by JonJagger** [comment]
Thanks. I look forward to the new gem. Till then I have a horrible work around!

**Comment by JonJagger** [comment]
Hi again,
its been a month and I'm really hoping for that new gem...
The current gem is basically unusable for any user that sets their warnings on... :(

**Comment by dmagliola** [comment]
Sorry about that! We've now merged all the relevant PRs, and we're pushing the new version to Rubygems today!

**Comment by JonJagger** [comment]
Thanks :-)
