### ISSUE TITLE
Running multiple Push Gateway instances

### ISSUE THREAD

**Issue by konfortes** [prometheus/client_ruby#200]
Hey guys,
When I'm running multiple instances (pods) of Prometheus push gateway, each one of them eventually ends up holding the whole registry, which makes sense because each call to `Prometheus::Client::Push#add` will be round-robined to one of the instances, adding the whole registry.

Maybe I can add an add_delta mechanism relying on timestamps?
What do you say?

**Comment by dmagliola** [comment]
Hi @konfortes,
Could you give us a bit more information about the use case you are going for? 
What would `add_delta` do? What is the outcome you are going for?

**Comment by konfortes** [comment]
The problem I'm trying to solve is a situation where a registry is being added more than once, resulting in duplicated values in different Prometheus push gateway instances.

After some code digging, I'm not sure the solution I thought about is applicable. Even with `delta_add` mechanism, it can still reach different instances.

Perhaps I should just change to a max PromQL query?

Do you think it should be documented?

**Comment by dmagliola** [comment]
Sorry for my late response.
If I understand correctly, you are trying to do this, to then `sum` the values from all your Push Gateways?
I don't believe that's how you should use the Push Gateway. I believe the `max by` you propose sounds better.
Please reopen this issue if you disagree.
