### ISSUE TITLE
Q: Is it possible to only use Pushgateway without having the /metrics?

### ISSUE THREAD

**Issue by fragkakis** [prometheus/client_ruby#203]
For my use case (pushing external metrics to Prometheus) I would like to only use the Push gateway functionality. I would like to skip having the `/metrics` endpoint, as well as the overhead of gathering the data for that endpoint. I will not be using it, at least not for now.

Is it possible to use the `client_ruby` gem only keeping the Push gateway part?

**Comment by SuperQ** [comment]
In order to use Prometheus correctly, you need to keep the metrics state anyway. Pushgateway or not. Prometheus is not designed to be a push system.

**Comment by fragkakis** [comment]
Thank you @SuperQ , I will try sending manually the data to push gateway for now and use the library when I need the `metrics` endpoint.
