### ISSUE TITLE
Document implications of negative observations for Summaries and Histograms

### ISSUE THREAD

**Issue by beorn7** [prometheus/client_ruby#218]
See https://github.com/prometheus/client_golang/issues/850 for details.

I'll create documentation on prometheus/docs, so that we only have to link to it.

**Comment by dmagliola** [comment]
Ah, interesting, that was an ommission!

Counters [validate that the increment is positive](https://github.com/prometheus/client_ruby/blob/master/lib/prometheus/client/counter.rb#L14)

[Histograms](https://github.com/prometheus/client_ruby/blob/master/lib/prometheus/client/histogram.rb#L58) and [Summaries](https://github.com/prometheus/client_ruby/blob/master/lib/prometheus/client/summary.rb#L20) do not.
I believe that is a bug that we should correct. We *should* validate that, correct?

Or is the right solution to continue to allow negative observations, and only document the implications?

**Comment by beorn7** [comment]
All official instrumentation libraries allow negative observations. I would keep that consistent.

You can still work perfectly with negative observations as long as you don't touch `..._sum`. For example, `histogram_quantile` calculations work just fine. OpenMetrics also allows negative observations, but requires the omission of `..._sum` in that case (at least I think that's what they intend, see https://github.com/OpenObservability/OpenMetrics/issues/193 ).

Plus, in the hopefully not too far future, Prometheus might very well support proper counter reset detection, and then we don't have to change things back.

**Comment by dmagliola** [comment]
That makes sense. I'll leave validations alone then and keep an eye on the other issue to link to the docs explaining it.

Thanks!

**Comment by beorn7** [comment]
https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations is the link to provide.
