### ISSUE TITLE
Travis-ci.org is no longer running

### ISSUE THREAD

**Issue by dmagliola** [prometheus/client_ruby#229]
We have lost CI on our PRs because of this. 

We need to migrate to travis-ci.com, [following these steps](https://docs.travis-ci.com/user/migrate/open-source-repository-migration), but I don't have the necessary permissions for this.

@SuperQ Would you be able help with this?

**Comment by SuperQ** [comment]
Sure, I can help.

We can also migrate this to CircleCI. All of the other Prometheus projects use CircleCI now.
