### ISSUE TITLE
Collector or Exporter outputs fluctuating data

### ISSUE THREAD

**Issue by harneksidhu** [prometheus/client_ruby#23]
I am using client_ruby in a rails application with the following config.ru file:

```
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)

# gzip compression
use Rack::Deflater

# metrics
require 'prometheus/client/rack/collector'
require 'prometheus/client/rack/exporter'

use Prometheus::Client::Rack::Collector
use Prometheus::Client::Rack::Exporter

run Storybook::Application
```

When analyzing counters such as `http_requests_total` or `http_request_duration_total_seconds`, I noticed that the values will fluctuate back and forth every few seconds. I confirmed this by constantly refreshing my `application.com/metrics` page and observing the values. My grafana dashboard caught this instantly. 

![image](https://cloud.githubusercontent.com/assets/1548575/16353903/104b093c-3a51-11e6-9fda-7570c2768817.png)

`http_requests_total` exhibits similar behaviour.

![image](https://cloud.githubusercontent.com/assets/1548575/16353915/3d91dbbe-3a51-11e6-878d-ddb045fbd284.png)

Are these fluctuations expected behaviour?

**Comment by grobie** [comment]
@harneksidhu I assume your rack application uses multiple processes? In that case read #9 for more information.
