### ISSUE TITLE
specifying ip-address and portnumber

### ISSUE THREAD

**Issue by devosalain** [prometheus/client_ruby#231]
I receive the error,
 http_requests has already been registered (Prometheus::Client::Registry::AlreadyRegisteredError)
I suppose I use an already used Ip-address/Port combination.
How do i specify both

**Comment by dmagliola** [comment]
Hello,
Could you show us some sample code, or provide a bit more context of what you are doing?

**Comment by devosalain** [comment]
My idea was to write a python client exporter for prometheus which spawns a webservice where prometheus can scrape the data of the gauges i write in this python program. Something like most existing exporters.
But for this i need to be able to specify the IP-address and port address.

Maybe another example to clarify. There exist a dovecot exporter for prometheus but you can specify the parameters.
"--web.listen-address="127.0.0.1:9166". So explicitly you can tell prometheus then to scrape on that IP-address and that specific port.
This is import in the case a port is already used by another instance which i think is in my case.
So my basic problem can be formulated as  :
from prometheus_client import start_http_server
Al good and well but I need to specify explicitly the IP-address and portnumber.
It seems the portnumber is an integer and as such, 8000 will work but not 127.0.0.1:8000 and that is important because I sit on a public interface routable over the internet so i must bind explicitly to 127.0.0.1.
if __name__ == '__main__':
    start_http_server(127.0.0.1:8000)
does not work, but is what i need.

**Comment by devosalain** [comment]
The following code seem to work except that it binds to all interfaces, but it allows me already to specify the port number

#!/usr/local/bin/python3.8
from prometheus_client import start_http_server, Summary
from prometheus_client import Gauge
import subprocess
import random
import time

g = Gauge('my_inprogress_requests', 'Description of gauge')

# Create a metric to track time spent and requests made.
REQUEST_TIME = Summary('request_processing_seconds', 'Time spent processing request')

# Decorate function with metric.
@REQUEST_TIME.time()
def process_request():
    global g
    print("Process request")
    g.set_to_current_time()   # Set to current unixtime
    g.inc()      # Increment by 1
    g.dec(10)    # Decrement by given value
    time.sleep(20)

if __name__ == '__main__':
    g.set(4.2)   # Set to a given value
    start_http_server(8000)
    while True:
        process_request()

**Comment by dmagliola** [comment]
Our exporter middleware will allow you to filter by port, once we release the new version (which should be soon), so that's half the use case you are looking for. To also filter by IP you'd have to make your own exporter, you can start by copying the one in our master branch, and then adding the IP filtering.

That said, the error you describe seems to be that the same metric is being registered twice. This sounds like you are adding the Collector middleware twice?

**Comment by devosalain** [comment]
Currently I have 80 tcp listeners running for different reasons, so probably that port was already occupied.
One final question. Could you guide me to which ruby file in this repo or which function within it where i can after cloning this repo hardcode an IP-address & Port. Probably this is the deepest function where not all parameters are given or the defaults are taken.

**Comment by dmagliola** [comment]
You don't need to clone the repo. The way our middleware works, you can just copy the contents of it into a file in your app, and add that middleware to Rack, you don't need to modify the gem, just point to your copy of the middleware instead.

This is the file you are looking for:
https://github.com/prometheus/client_ruby/blob/master/lib/prometheus/middleware/exporter.rb

That said, I still think the error you are receiving is not a "two things tried to open the same port". That error is "the same metric got registered twice".

**Comment by Sinjo** [comment]
Closing this as it's stale, and I think wasn't for something our gem would handle in the first place.

> Luckely the python api knows : "start_http_server(addr="127.0.0.1",port=38000)", but the ruby equivalent would be nice to have.

We don't start any HTTP servers directly in the gem, and by extension don't bind to any network interfaces.
