### ISSUE TITLE
Exporter port option doesn't work

### ISSUE THREAD

**Issue by dmcnmrk** [prometheus/client_ruby#250]
```
#config.ru
require 'rack'
require 'prometheus/middleware/collector'
require 'prometheus/middleware/exporter'

use Rack::Deflater
use Prometheus::Middleware::Collector
use Prometheus::Middleware::Exporter, {:port => 3010} #<-- port doesn't override
```
**expected:**
can resolve metrics at 'localhost:3010/metrics'

**result:** 
localhost refused to connect.

:path option overrides correctly; e.g. 'localhost:3000/mymetrics' returns metrics as expected
```use Prometheus::Middleware::Exporter, {:path => '/mymetrics'}```

**Comment by dmagliola** [comment]
I'm not sure if I understanding correctly, but I'm going by this comment: "localhost refused to connect."

The port option will act as a filter, such that only requests coming through that port will get metrics served, and others will get passed through your app.

However, it will not open the port for you. You'll need to do that part in your web server configuration.

Did I understood the issue correctly?

**Comment by dmagliola** [comment]
I’m closing this as “responded”
