### ISSUE TITLE
cannot load such file -- prometheus/middleware/collector (LoadError)

### ISSUE THREAD

**Issue by DerekCrosson** [prometheus/client_ruby#293]
When running the config.ru code in the readme I get the following error:

cannot load such file -- prometheus/middleware/collector (LoadError)

This happens because the required files and namespaces have changed.|

This PR updates the readme to provide code that works: https://github.com/prometheus/client_ruby/pull/294

**Comment by Sinjo** [comment]
Closing this and the assosiated PR as I'm pretty sure those paths are from an older version. Feel free to reopen if there's an issue with the current version.
