### ISSUE TITLE
/metrics returning JSON

### ISSUE THREAD

**Issue by deepthawtz** [prometheus/client_ruby#30]
```json
[
  {
    "baseLabels": {
      "__name__": "http_requests_total"
    },
    "docstring": "A counter of the total number of HTTP requests made.",
    "metric": {
      "type": "counter",
      "value": [
        {
          "labels": {
            "method": "get",
            "path": "/metrics",
            "code": "200"
          },
          "value": 6
        },
        {
          "labels": {
            "method": "get",
            "path": "/",
            "code": "200"
          },
          "value": 11
        }
      ]
    }
  },
  {
    "baseLabels": {
      "__name__": "http_request_durations_total_microseconds"
    },
    "docstring": "The total amount of time spent answering HTTP requests (microseconds).",
    "metric": {
      "type": "counter",
      "value": [
        {
          "labels": {
            "method": "get",
            "path": "/metrics",
            "code": "200"
          },
          "value": 4057
        },
        {
          "labels": {
            "method": "get",
            "path": "/",
            "code": "200"
          },
          "value": 27355
        }
      ]
    }
  },
  {
    "baseLabels": {
      "__name__": "http_request_durations_microseconds"
    },
    "docstring": "A histogram of the response latency (microseconds).",
    "metric": {
      "type": "histogram",
      "value": [
        {
          "labels": {
            "method": "get",
            "path": "/metrics",
            "code": "200"
          },
          "value": {
            "0.5": 609,
            "0.9": 652,
            "0.99": 652
          }
        },
        {
          "labels": {
            "method": "get",
            "path": "/",
            "code": "200"
          },
          "value": {
            "0.5": 1492,
            "0.9": 1628,
            "0.99": 1628
          }
        }
      ]
    }
  },
  {
    "baseLabels": {
      "__name__": "http_exceptions_total"
    },
    "docstring": "A counter of the total number of exceptions raised.",
    "metric": {
      "type": "counter",
      "value": []
    }
  }
]
```

I've included Prometheus rack middleware in a new Rails app and /metrics returns JSON. Is this normal/expected?

**Comment by deepthawtz** [comment]
maybe this is OK (Prometheus can ingest this JSON) but confused me because in a bare Rack app /metrics is returned in plain text.

**Comment by grobie** [comment]
@deepthawtz Which client version do you use? JSON support has been removed in v0.5.0 https://github.com/prometheus/client_ruby/releases/tag/v0.5.0

**Comment by grobie** [comment]
Text format was added in v0.3.0, so you seem to use a version between v0.3.0 and v0.5.0. The server uses HTTP content negotiation and will prefer text over json. The Prometheus server >= v1.0.0 doesn't support JSON anymore.

I strongly suggest to update your client library version, also have a look at the README. It's recommended to add a Gzip middleware as described there.

**Comment by deepthawtz** [comment]
in my `Gemfile.lock` I see `prometheus-client (0.6.0)`

**Comment by deepthawtz** [comment]
steps to reproduce:

1. `rails new poo`
1. add `gem 'prometheus-client'` to Gemfile && `bundle install`
1. update `config/application.rb` and add ```ruby
require "prometheus/client/rack/collector"
require "prometheus/client/rack/exporter"
# ... in Rails::Application configuration
   config.middleware.use Prometheus::Client::Rack::Collector
   config.middleware.use Prometheus::Client::Rack::Exporter
```

**Comment by deepthawtz** [comment]
ah... basically won't work w/o `Rack::Deflater` I see now.. thanks

**Comment by grobie** [comment]
@deepthawtz What? How's that possible, the code path to respond with JSON is not longer available in v0.6.0. Can you double check that you don't have an older gem version installed and that your server really uses 0.6.0? Maybe log the client version `puts Prometheus::Client::VERSION`.

Please re-open if you see a 0.6.0 client responding with JSON format.

**Comment by deepthawtz** [comment]
odd. I see:

```uninitialized constant Prometheus::Client::VERSION (NameError)```

but

```gem list | grep prometheus
prometheus-client (0.6.0)```

no other versions are installed

and the prometheus-client code on disk definitely has `lib/prometheus/client/version.rb`

still digging...

**Comment by grobie** [comment]
You might need to require the file first: `require
'prometheus/client/version'; puts Prometheus::Client::VERSION`.
