### ISSUE TITLE
Right time to Pushgateway with background job processing like Sidekiq?

### ISSUE THREAD

**Issue by zevarito** [prometheus/client_ruby#34]
I wonder which is the right time to push metrics in a background job system like Sidekiq, seems too much to do it after each job completes/fail, a cronjob or scheduled task is better? how often?

I have the understanding that Sidekiq uses threads so registry will be available for every job as long the process is running, but I wonder what happen with scheduled jobs, perhaps this question is more for Sidekiq but some of you might be already answered yourself this.

Thanks!

**Comment by brian-brazil** [comment]
For typical Sidekiq uses, you'd not want to use the pushgateway. Rather have Sidekiq expose a running count of job success/failures and scrape that.

**Comment by zevarito** [comment]
@brian-brazil What do you mean with Sidekiq exposing? I know that Sidekiq has a pretty good monitor system, is that what you say to use?

**Comment by zevarito** [comment]
@brian-brazil did you already do something like this?

Say I found a Sidekiq entry point where I can bring up Rack Collector just when Sidekiq starts, since Sidekiq is multi-threaded, jobs should be able to access the same registry, so should I "constantize/globalize" a regisitry instance and then use that on every job?

**Comment by brian-brazil** [comment]
The global registry is already handled for you by the Ruby client. All you'll need to do is expose /metrics.

**Comment by zevarito** [comment]
Right, that was my first approach, but callbacks like `after_perform` (notice that comes from ActiveJob, it is a Rails app) are called, but registry is not updated, yes it is updated when measuring from `before_enqueue` callback which is called outside Sidekiq process context.
