### ISSUE TITLE
Pre-release 0.7.0

### ISSUE THREAD

**Issue by Strech** [prometheus/client_ruby#46]
Hey guys, your library is awesome!

Can I ask you for a favour to release `rc1` or so for `0.7.0` version? Unfortunately our project can't use the master branch from the Github. But in current the master, you have super exciting and important changes.

**Comment by grobie** [comment]
@Strech Yes, it's totally on my list. I wanted to squeeze in a few more validations into `0.7.0`. I'm happy to release a rc1 version on rubygems today though. Even better if there are people who are willing to try it!

**Comment by grobie** [comment]
Here you go! https://rubygems.org/gems/prometheus-client/versions/0.7.0.pre.rc.1

**Comment by Strech** [comment]
@grobie Awesome, thanks! ❤️
