### ISSUE TITLE
Histogram is really a cumulative histogram

### ISSUE THREAD

**Issue by defsprite** [prometheus/client_ruby#48]
In contrast to other prometheus clients (i.e. golang) the histogram does not use _disjoint_ buckets but cumulative values (see https://github.com/prometheus/client_ruby/blob/master/lib/prometheus/client/histogram.rb#L28)

While this is also a nice way to collect metrics, it should be named as `CumulativeHistogram` and `Histogram` should behave as other client libraries do, as this can be confusing, especially when using quantile conversion.

**Comment by brian-brazil** [comment]
This is the same as other clients, just implemented a different way.

**Comment by grobie** [comment]
All Prometheus histograms are cumulative by [definition](https://prometheus.io/docs/concepts/metric_types/#histogram). The golang library does this later in the Write() method. The ruby client library will follow suit once #36 is implemented (e.g. after the big rewrite).

**Comment by defsprite** [comment]
I stand corrected. Sorry for bugging you and thanks for the help!
