### ISSUE TITLE
README.md for stable version

### ISSUE THREAD

**Issue by igorvpcleao** [prometheus/client_ruby#52]
I think it would be nice to have the README.md showing instructions to the most recent stable version.
If I go to `github.com/prometheus/client_ruby` and look at the README.md, those are not the instructions for the most recent stable version.

**Comment by grobie** [comment]
Agreed, the inconsistency is not great. I'll release 0.7.0 this week.

**Comment by albertogg** [comment]
hi @grobie, when is 0.7.0 releasing?

Thanks,

**Comment by grobie** [comment]
I just released v0.7.0.

**Comment by albertogg** [comment]
Thank you! @grobie
