### ISSUE TITLE
Can't get custom metrics to work in Rails App

### ISSUE THREAD

**Issue by mdesanti** [prometheus/client_ruby#53]
Hi!

I've configured the gem in a Rails App and default metrics seem to be working fine. However, If I try to do something like this:

```
  def index
    gauge = Prometheus::Client::Gauge.new(:room_temperature_celsius, '...')
    gauge.set({ room: 'kitchen' }, 21.534)

    result = User.find_by(username: params[:username])
    if result.nil?
      render json: { msg: 'Error user name not found' }, status: :not_found
    else
      render json: result
    end
  end
```

The metric does not show in `/metrics` path.

Is there any I'm doing wrong? 
Thank you!

**Comment by grobie** [comment]
You did not register the created gauge metric with the registry. See the readme for an explanation.

Metrics shouldn't be created inside of a Rails action method, as these will be called during every request. Instead, register the metrics once and keep a reference to it.
