### ISSUE TITLE
Metric uniqueness check uses only metric name.

### ISSUE THREAD

**Issue by pawelchcki** [prometheus/client_ruby#55]
In go client hash of labels and metric name is used to check uniqueness.
https://github.com/prometheus/client_golang/blob/master/prometheus/desc.go#L71

In Ruby client it's not the case and only metric name is used to identify unique metrics.

**Comment by grobie** [comment]
Agreed. The main issue is that with the ruby client library you don't even pre-register the labels you're going to use and the concept of const labels doesn't really exist. This won't be solved before the major rewrite.

**Comment by brian-brazil** [comment]
Const labels are particular to the Go client, which also does more sanity checking than any other client.

**Comment by dmagliola** [comment]
We now support (actually require) pre-declaring the labels. I believe this solves the issue?
Please reopen if I've misunderstood this.
