### ISSUE TITLE
Correct way to instantiate Registries

### ISSUE THREAD

**Issue by gargath** [prometheus/client_ruby#56]
I am trying to use the promethus client in a Rack application using Grape.

Since Grape APIs do not have an `initialize` block, I am somewhat lost as to what the best place is to create the Registry and register metrics.

Am I meant to only ever use a single `Client::Registry` throughout my code or can I create new ones where I need them?
Will they share the registered metrics?

I suspect not, and if that is correct, I would appreciate some pointers as to the preferred way of handling the Registry. Should I wrap it in a Singleton?

**Comment by grobie** [comment]
Usually you only use one registration per application. The client library provides you with a singleton already `Prometheus::Client.registry`.

**Comment by gargath** [comment]
So it does... I had completely missed that.
Thank you very much :)
