### ISSUE TITLE
delete or remove method in ruby-client

### ISSUE THREAD

**Issue by wdp-007** [prometheus/client_ruby#64]
I did not find delete or remove method in ruby-client, like gauge:
gauge.set({ room: 'kitchen' }, 21.534)
gauge.get({ room: 'kitchen' })
Is there any gauge.delete or gauge.remove method? I did not find this in the source code also.

**Comment by wdp-007** [comment]
Or is there any way or parameter to make metrics expire?

**Comment by grobie** [comment]
For direct instrumentation, no labels should be used which need to get removed again. This is usually a sign for wrong instrumentation.

There are valid use cases though, which almost all fall into the use case of writing exporters. client_ruby is currently not well suited to well suited for that, until the collector interface has been implemented https://github.com/prometheus/client_ruby/issues/36.
