### ISSUE TITLE
Release v0.7.2?

### ISSUE THREAD

**Issue by jwhitcraft** [prometheus/client_ruby#73]
Would it be possible to release the latest master since it's been sitting for 4 months?

Thanks.

**Comment by klippx** [comment]
My thinking exactly 🥇

**Comment by klippx** [comment]
I am writing a lib that depends on that .increment and .decrement on Gauge, would be great if you could see it mature for a release

**Comment by klippx** [comment]
🏏

**Comment by grobie** [comment]
v0.8.0 has been released and pushed to rubygems https://github.com/prometheus/client_ruby/releases/tag/v0.8.0
