### ISSUE TITLE
Metrics_prefix not available in released version

### ISSUE THREAD

**Issue by luongvo209** [prometheus/client_ruby#79]
Hi, first of all, I would like to thank you for your awesome work. 

I found 
```ruby
@metrics_prefix = options[:metrics_prefix] || 'http_server'
…
```

inside of `lib/prometheus/middleware/collector.rb` which enables users of this gem to customize the prefix of some default metrics. 

However, this line does not present in the released version of this gem (*latest version 0.7.1*). After downloading the gem and view the source,  I cannot find the equivalent line :   

![image](https://user-images.githubusercontent.com/15828926/35444995-d632d980-02e2-11e8-8c49-b2db4dd96f17.png)

**Comment by alexjesp** [comment]
I have the same issue!

**Comment by luongvo209** [comment]
@alexjesp  It's a nice  feature that is missing but the maintainers seem not interested in this issue. I suggest that you handle it yourself, either by monkey patching Prometheus code or just hard coding your desired prefix. :)

**Comment by alexjesp** [comment]
Yeah, I’ve gem installed at the commit hash for now. 🙏🏻 Thanks!

**Comment by ralberto** [comment]
Same issue here...
