### ISSUE TITLE
Full example code for historgram/summary?

### ISSUE THREAD

**Issue by omurbekjk** [prometheus/client_ruby#84]
I am newbie with prometheus. I wanted to test histogram & summary with `pushgateway`.
Readme was not helpful for me to setup basic histogram/summary metrics.
I think it will be very helpful to add basic example to `examples` directory.

**Comment by grobie** [comment]
If you need support, please send your questions to the [prometheus-users](https://groups.google.com/forum/#!forum/prometheus-users) mailing list rather than filing a GitHub issue. See https://prometheus.io/community/ for more information.
