### ISSUE TITLE
Push uses legacy API

### ISSUE THREAD

**Issue by cwndrws** [prometheus/client_ruby#98]
The API that this client uses to push metrics to a push gateway was deprecated and then removed in this [commit](https://github.com/prometheus/pushgateway/commit/4c1bf91117b14b90ed17bc39b91ec49d721d716a#diff-7ddfb3e035b42cd70649cc33393fe32c). Push from this client to newer versions of the push gateway fail with a `404 Not Found` error.

**Comment by cwndrws** [comment]
I'm about to submit a new PR that uses the new API.

**Comment by beorn7** [comment]
Ouch. I'm very sorry. When removing the legacy API, I thought all official client libraries had been updated already. @grobie could you have a look it the PR #99 ?

**Comment by beorn7** [comment]
Fixed by #102

**Comment by cwndrws** [comment]
@beorn7 are you planning on cutting a release that contains this soon?

**Comment by grobie** [comment]
I'm gonna do that now.
